-- EXEMPLO 1: SELECIONANDO TODAS AS LINHAS E COLUNAS DA:
-- A) DA TABELA PEDIDOS

SELECT * FROM pedidos;

-- B) DA TABELA DE CLIENTES
select * FROM clientes;

-- EXEMPLO 2: SELECIONAR APENAS ALGUMAS COLUNAS DA TABELA CLIENTES

SELECT 
	ID_cliente AS 'ID Cliente', 
	Nome AS 'Nome do cliente',
    Data_Nascimento AS 'Data de Nascimento',
    Email AS 'E-mail do cliente'
FROM clientes;

-- EXEMPLO 3: SELECIONAR AS 5 PRIMEIRAS LINHAS DA TABELA DE PRODUTOS

SELECT * FROM produtos
LIMIT 5;

-- EXEMPLO 4: SELECIONAR TODAS AS LINHAS DA TABELA PRODUTOS MAS...
-- ORDENANDO PELA COLUNA DE Preço_Unit

SELECT * FROM produtos
ORDER BY Preco_Unit ASC;

-- ASC = DO MENOR PARA O MAIOR
-- DESC = DO MAIOR PARA O MENOR


