-- O GROUP BY É UM COMANDO DO SQL QUE VAI NOS PERMITIR  CRIAR AGRUPAMENTOS, OU SEJA, TABELAS
-- RESUMOS DAS NOSSA TABELAS PRINCIPAIS

-- EXEMPLO 1: UTILIZE O GROUP BY PARA CRIARR UMA ACONSULTA E DESCOBRIR O TOTAL DE CLIENTES POR SEXO


SELECT * FROM clientes;

SELECT Sexo, COUNT(*) AS 'Qtd. Clientes' FROM clientes
ORDER BY Sexo;

-- EXEMPLO 2: FAÇA UMA CONSULTA À TABELA DE PRODUTOS PARA RETORNAR O TOTAL DE PRODUTOS MARCA

SELECT * FROM produtos;

SELECT Marca_Produto, COUNT(*) AS 'Qtd. Produtos' FROM produtos
GROUP BY Marca_Produto;

-- EXEMPLO 3: FAÇCA UMA CONSULTA À TABELA PEDIDOS E DESCUBRA A RECEITA TOTAL E CUSTO TOTAL POR ID_LOJA

SELECT * FROM Pedidos;

SELECT
	ID_Loja,
    Sum(Receita_Venda) AS 'Receita Total',
    SUM(Custo_venda) AS 'Custo Total'
FROM pedidos
GROUP BY ID_Loja;